### ISSUE TITLE
Error refreshing classpath registry

### ISSUE THREAD

**Issue by daptordarattler** [noseglid/java-classpath-registry#1]
When I do refresh, I always get this error. My project is a grails based project with java classes. What do I do?
![image](https://cloud.githubusercontent.com/assets/1119455/16440682/8bdc9f4c-3d9a-11e6-949c-3bbc606c0662.png)

**Comment by noseglid** [comment]
So how many open projects do you have?

**Comment by daptordarattler** [comment]
I just noticed that I had 2 folders open, but one was a subfolder of the
other...

I am removing it and trying the plugin again...

1, 2, 4, 5, 6....

Ah, it works now.... Thanks :-)
