### ISSUE TITLE
EACCES: permission denied, scandir '/System/Library/User Template'

### ISSUE THREAD

**Issue by xinstein** [noseglid/java-classpath-registry#4]
I encounter this problem when trying to refresh class path

My .classpath file contains a single dot indicating the current directory only.

What I'm trying to do is to let my classes complete each other, what should I do?

**Comment by noseglid** [comment]
Dot is unfortunately not the current directory of the classpath file. It is the working directory of Atom (which I suspect is `/` for you). 

You should have a fully qualified path. If you're using `linter-javac` or such, which automatically compiles the files, you could set the output of in your `.classpath` file.
